[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "latimes-calculate>=0.3.1",
    "pandas>=2.2.3",
]
